### ISSUE TITLE
Create storage mechanism for rules, etc.

### ISSUE THREAD

**Issue by jbukhari** [dag-hammarskjold-library/itp-process#23] opened 2019-09-11 15:25 UTC
Possible usage: `rule.store()` where `rule` is a Rule object and `store()` is a method defined in the Rule class. TBD.

**Comment by aaronhelton** [comment] 2019-09-11 15:27
Take a look at https://github.com/dag-hammarskjold-library/itp-process/blob/routes/app/models.py

**Comment by aaronhelton** [comment] 2019-09-16 20:02
This is almost a duplicate of #24

**Comment by aaronhelton** [comment] 2019-10-17 15:47
This is completed

**Closed by aaronhelton** 2019-10-17 15:47 UTC
